# Example configuration
max_iterations: 1000

llm:
  primary_model: "gpt-4.1-mini"
  temperature: 0.7

  # API configuration
  api_base: "https://api.openai.com/v1"         # Base URL for API
  api_key: "<YOUR SECRET KEY HERE>"                       # API key (defaults to OPENAI_API_KEY env variable)

database:
  population_size: 500
  num_islands: 5
